# src/training/trainer.py
# eac-net training loop — infonce contrastive loss.
#
# objective: for a point f_i on fragment a's contour, its true match f_i+ on
# fragment b must be closer in embedding space than all other points (negatives).
# loss = -log [ exp(sim(f_i, f_i+) / τ) / Σ_j exp(sim(f_i, f_j) / τ) ]
#
# after training, save weights to checkpoints/ and set features.weights_path in config.

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import cv2
import numpy as np
from pathlib import Path
import json

from src.features.eac_net        import build_model
from src.features.geometry       import compute_geometric_features
from src.features.texture_strip  import extract_texture_strip
from src.segmentation.segmenter  import _resample_equidistant


# ── infonce loss ──────────────────────────────────────────────────────────────

class infonce_loss(nn.Module):
    """symmetric infonce for a batch of matched fragment pairs.

    for each point on fragment a, the corresponding point on fragment b is the
    positive; all other points in the batch are negatives.
    """

    def __init__(self, temperature: float = 0.07):
        super().__init__()
        self.tau = temperature

    def forward(self, emb_a: torch.Tensor, emb_b: torch.Tensor) -> torch.Tensor:
        """
        emb_a, emb_b: (batch * n_pts, embed_dim) — l2-normalized point embeddings
                       row i in emb_a matches row i in emb_b.
        """
        # similarity matrix: (b*n, b*n)
        sim = torch.mm(emb_a, emb_b.T) / self.tau

        # diagonal = positive pairs; off-diagonal = negatives
        labels = torch.arange(len(emb_a), device=emb_a.device)

        # symmetric: a→b and b→a both contribute
        loss = (F.cross_entropy(sim, labels) + F.cross_entropy(sim.T, labels)) / 2
        return loss


# ── dataset ───────────────────────────────────────────────────────────────────

class fragment_pair_dataset(Dataset):
    """loads synthetic fragment pairs and returns aligned geometry+texture features."""

    def __init__(self, metadata: list, strip_width: int = 16, n_pts: int = 512):
        self.meta       = metadata
        self.strip_w    = strip_width
        self.n_pts      = n_pts

    def __len__(self) -> int:
        return len(self.meta)

    def __getitem__(self, idx: int) -> dict:
        m     = self.meta[idx]
        img_l = cv2.imread(m["left"],  cv2.IMREAD_COLOR)
        img_r = cv2.imread(m["right"], cv2.IMREAD_COLOR)

        # convert to rgba with full-opacity alpha (no segmentation needed for synth)
        def to_rgba(img):
            rgba = cv2.cvtColor(img, cv2.COLOR_BGR2RGBA)
            rgba[:, :, 3] = 255
            return rgba

        rgba_l, rgba_r = to_rgba(img_l), to_rgba(img_r)

        # use the ground-truth shared cut boundary as the matching contour
        cut = np.array(m["cut_pts"], dtype=np.float32)

        geo_l = compute_geometric_features(cut)
        geo_r = compute_geometric_features(cut)   # same geometry — shared boundary

        tex_l = extract_texture_strip(rgba_l, cut, self.strip_w)
        tex_r = extract_texture_strip(rgba_r, cut, self.strip_w)

        return {
            "geo_l":   torch.from_numpy(geo_l),   # (n, 5)
            "tex_l":   torch.from_numpy(tex_l),   # (n, sw, 3)
            "geo_r":   torch.from_numpy(geo_r),
            "tex_r":   torch.from_numpy(tex_r),
        }


# ── training loop ─────────────────────────────────────────────────────────────

def train(cfg: dict):
    """main training entry point — call from train.py."""
    tc     = cfg["training"]
    fc     = cfg["features"]
    device = torch.device(fc.get("device", "cpu"))

    # load metadata generated by synth_generator
    meta_path = Path(tc["out_dir"]) / "metadata.json"
    if not meta_path.exists():
        raise FileNotFoundError(
            f"no metadata.json at {meta_path} — run: python train.py --generate-data"
        )
    with open(meta_path) as f:
        metadata = json.load(f)

    dataset    = fragment_pair_dataset(metadata, fc["strip_width"])
    loader     = DataLoader(dataset, batch_size=tc["batch_size"],
                            shuffle=True, num_workers=0, pin_memory=False)

    model      = build_model(cfg).to(device)
    optimizer  = torch.optim.AdamW(model.parameters(), lr=tc["lr"], weight_decay=1e-4)
    criterion  = infonce_loss(temperature=tc["temperature"])
    scheduler  = torch.optim.lr_scheduler.CosineAnnealingLR(
                    optimizer, T_max=tc["epochs"])

    ckpt_dir   = Path(tc["checkpoint_dir"])
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    best_loss  = float("inf")

    for epoch in range(1, tc["epochs"] + 1):
        model.train()
        total_loss = 0.0

        for batch in loader:
            geo_l  = batch["geo_l"].to(device)
            tex_l  = batch["tex_l"].to(device)
            geo_r  = batch["geo_r"].to(device)
            tex_r  = batch["tex_r"].to(device)

            # forward pass: (batch, n, embed_dim) each
            emb_l  = model(geo_l, tex_l)
            emb_r  = model(geo_r, tex_r)

            # flatten batch and point dims: (batch*n, embed_dim)
            b, n, d = emb_l.shape
            emb_l   = emb_l.reshape(b * n, d)
            emb_r   = emb_r.reshape(b * n, d)

            loss = criterion(emb_l, emb_r)
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            total_loss += loss.item()

        scheduler.step()
        avg = total_loss / max(1, len(loader))
        print(f"[trainer] epoch {epoch:03d}/{tc['epochs']} — loss {avg:.4f}")

        if avg < best_loss:
            best_loss = avg
            ckpt_path = ckpt_dir / "eac_net_best.pt"
            torch.save({"epoch": epoch, "loss": avg, "model": model.state_dict()}, ckpt_path)
            print(f"[trainer] checkpoint saved → {ckpt_path}")

    print(f"[trainer] training done — best loss {best_loss:.4f}")
    print(f"[trainer] set features.weights_path: \"{ckpt_dir}/eac_net_best.pt\" in config.yaml")